effective_activism.settings:
  type: config_object
  label: 'Effective Activism settings'
  mapping:
    google_maps_api_key:
      type: string
      label: 'The Google Maps API key'
    google_static_maps_api_key:
      type: string
      label: 'The Google Static Maps API key'
    darksky_api_key:
      type: string
      label: 'The Darksky API key'
