effective_activism.settings:
  type: config_object
  label: 'Effective Activism settings'
  mapping:
    google_maps_api_key:
      type: string
      label: 'The Google Maps API key'
    google_static_maps_api_key:
      type: string
      label: 'The Google Static Maps API key'
    darksky_api_key:
      type: string
      label: 'The Darksky API key'
    arcgis_client_id:
      type: string
      label: 'The ArcGis client id'
    arcgis_client_secret:
      type: string
      label: 'The ArcGis secret'
    arcgis_access_token:
      type: string
      label: 'The ArcGis Access token'
    arcgis_access_token_timestamp:
      type: integer
      label: 'The ArcGis token generation timestamp'
