effective_activism.export_type.*:
  type: config_entity
  label: 'Export type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
